book_shop/book_shop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='library')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shop/library/urls.py
from django.contrib import admin
from django.urls import path
#from .views import index_view
from .views import BookView, BookDetailView

app_name = 'library'

urlpatterns = [
    path('', BookView.as_view(), name='index'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
]

book_shop/library/models.py
from django.db import models


class PublishingHouse(models.Model):
    name = models.CharField(max_length=32, unique=True)
    address = models.CharField(max_length=256)

    class Meta:
        unique_together = ['name', 'address']


class Author(models.Model):
    name = models.CharField(max_length=64)
    birthdate = models.DateField(null=True, blank=True)
    is_man = models.BooleanField(default=True)
    about = models.TextField(null=True)

    unique_together = ['name', 'birthdate']


class Review(models.Model):
    about_book = models.TextField(blank=True)
    author_review = models.ForeignKey(Author, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.about_book

    def review_count(self):
        return Review.objects.count()


class Book(models.Model):
    author = models.ManyToManyField(Author)
    release = models.DateField(null=False)
    publishing_house = models.ForeignKey(PublishingHouse, on_delete=models.PROTECT)
    isbn = models.IntegerField(unique=True)
    name_book = models.CharField(max_length=256, null=False)
    review = models.ManyToManyField(Review)
    image = models.ImageField(upload_to='book', blank=True, null=True)

    def __str__(self):
        return self.name_book

book_shop/library/views.py
from django.shortcuts import render
from .models import Book
from django.views.generic import ListView, DetailView, View


class BookView(ListView):
    # model = Book
    template_name = 'library/allbook.html'
    context_object_name = 'all_books'
    queryset = Book.objects.prefetch_related('author', 'review').all()


class BookDetailView(DetailView):
    queryset = Book.objects.prefetch_related('author', 'review').all()
    context_object_name = 'book'
    template_name = 'library/allbook_detail.html'

book_shop/library/templates/library/allbook.html
{% extends "base.html" %}
{% block title %}Все книги{% endblock %}
{% block main %}
<h1>Наши книги:</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Название книги</th>
        <th scope="col">Авторы</th>
        <th scope="col">Обложка</th>
        <th scope="col">О книге</th>
    </tr>
    </thead>
    <tbody>
    {% for book in all_books %}
    <tr>
        <th scope="row">{{ book.name_book }}</th>
        <td>
            <ul class="list-group list-group-flush">
                {% for auth in book.author.all %}
                <li class="list-group-item">{{ auth.name }}</li>
                {% endfor %}
            </ul>
        </td>
        <td>
            {% if book.image %}
            <img width="150px" src="{{ book.image.url }}">
            {% endif %}
        </td>
        <td>
            <a href="{% url 'library:book_detail' book.pk %}">Подробнее</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

book_shop/library/templates/library/allbook_detail.html
{% extends "base.html" %}
{% block title %}Подробнее{% endblock %}

{% block main %}

<div align="center">
    <h1>{{ book.name_book }}</h1>
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{ book.image.url }}" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">{{ book.name_book }}</h5>
        <p class="card-text">Отызывы:
        <ul>
            {% for rew in book.review.all %}
            <li>{{ rew.about_book }}</li>
            {% endfor %}
        </ul>
        </p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">isbn: {{ book.isbn }}</li>
        <li class="list-group-item">Год издательства: {{ book.release }}</li>
        <li class="list-group-item">Издательство: {{ book.publishing_house.name }} ({{ book.publishing_house.address }}) </li>
    </ul>
    <div class="card-body">
        <a href="{% url 'library:index' %}" class="card-link">К книгам</a>
    </div>
</div>
</div>

{% endblock %}

book_shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Библиотека</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Доставка <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Новинки</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Бестселлеры</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container-fluid">
{% block main %}
{% endblock %}
</div>


</body>
</html>